import { builtInGradients, defineTheme } from "../schema";

/**
 * HM Froid "Inox": the site takes its material from the catalogue. Polished
 * steel, graphite, paper white, and one cobalt accent carried over from the
 * old blue. Steel is never a flat fill, only the `brushed` and `polished`
 * gradients on a `plate` section, so it reads as metal and not as grey.
 */
export const hmFroidTheme = defineTheme({
  id: "hm-froid",
  name: "HM Froid Inox",
  description: "Brushed stainless steel, graphite and paper white with a single cobalt accent. Sharp but safe: 3px radius, hairline borders.",
  modeStrategy: "light",
  palette: [
    { id: "cobalt", name: "Cobalt", group: "brand", locked: true, value: "oklch(0.47 0.17 258)", description: "The one accent: buttons, links, status. Inherits the old HM blue." },
    { id: "cobalt-light", name: "Cobalt light", group: "brand", value: "oklch(0.8 0.08 255)", description: "Links and eyebrows on graphite." },
    { id: "steel", name: "Steel", group: "accent", value: "oklch(0.82 0.008 240)", description: "Plate background. Only ever shown through the brushed or polished gradient." },
    { id: "steel-dark", name: "Steel dark", group: "accent", value: "oklch(0.62 0.01 240)", description: "Shadow side of the plate; borders on steel." },
    { id: "chrome", name: "Chrome", group: "accent", value: "oklch(0.94 0.005 235)", description: "Highlight sweep on steel; raised surfaces on the plate." },
    { id: "paper", name: "Paper", group: "neutral", value: "oklch(0.975 0.004 230)", description: "Page background. Not pure white." },
    { id: "paper-card", name: "Paper card", group: "neutral", value: "oklch(0.995 0.002 230)", description: "Cards and inputs on paper." },
    { id: "line", name: "Hairline", group: "neutral", value: "oklch(0.88 0.008 240)", description: "Borders on paper." },
    { id: "ash", name: "Ash", group: "neutral", value: "oklch(0.46 0.015 250)", description: "Muted text on paper." },
    { id: "graphite", name: "Graphite", group: "neutral", value: "oklch(0.2 0.012 250)", description: "Body text; dark bands (hero plinth, footer)." },
    { id: "graphite-raised", name: "Graphite raised", group: "neutral", value: "oklch(0.27 0.012 250)", description: "Cards on graphite." },
    { id: "graphite-line", name: "Graphite line", group: "neutral", value: "oklch(0.36 0.012 250)", description: "Borders on graphite." },
  ],
  schemes: [
    {
      id: "paper",
      name: "Paper canvas",
      description: "Default page background. Catalogue, text pages, forms.",
      light: {
        background: "paper",
        backgroundAlt: "chrome",
        text: "graphite",
        textMuted: "ash",
        heading: "graphite",
        primary: "cobalt",
        onPrimary: "paper-card",
        secondary: "graphite",
        onSecondary: "paper-card",
        surface: "paper-card",
        onSurface: "graphite",
        accent: "steel",
        onAccent: "graphite",
        accentText: "cobalt",
        border: "line",
        link: "cobalt",
        focusRing: "cobalt",
      },
    },
    {
      id: "plate",
      name: "Steel plate",
      description: "The metal: hero, CTA band, product-card hover. Pair with the brushed or polished gradient and the brushed-lines texture.",
      light: {
        background: "steel",
        backgroundAlt: "steel-dark",
        text: "graphite",
        textMuted: { token: "graphite", mix: { alpha: 0.72 } },
        heading: "graphite",
        primary: "graphite",
        onPrimary: "chrome",
        secondary: "cobalt",
        onSecondary: "paper-card",
        surface: "chrome",
        onSurface: "graphite",
        accent: "graphite",
        onAccent: "chrome",
        accentText: { token: "cobalt", mix: { lightness: -0.07 } },
        border: "steel-dark",
        link: "graphite",
        focusRing: "cobalt",
      },
    },
    {
      id: "graphite",
      name: "Graphite band",
      description: "Dark bands: hero plinth, footer, trust strip.",
      light: {
        background: "graphite",
        backgroundAlt: "graphite-raised",
        text: "chrome",
        textMuted: "steel",
        heading: "paper-card",
        primary: "chrome",
        onPrimary: "graphite",
        secondary: "cobalt-light",
        onSecondary: "graphite",
        surface: "graphite-raised",
        onSurface: "chrome",
        accent: "cobalt",
        onAccent: "paper-card",
        accentText: "cobalt-light",
        border: "graphite-line",
        link: "cobalt-light",
        focusRing: "cobalt-light",
      },
    },
    {
      id: "cobalt",
      name: "Cobalt accent",
      description: "One band per page at most: rachat offer, newsletter.",
      light: {
        background: "cobalt",
        backgroundAlt: "cobalt",
        text: "paper-card",
        textMuted: { token: "paper-card", mix: { alpha: 0.8 } },
        heading: "paper-card",
        primary: "paper-card",
        onPrimary: "cobalt",
        secondary: "graphite",
        onSecondary: "paper-card",
        surface: { token: "cobalt", mix: { lightness: -0.08 } },
        onSurface: "paper-card",
        accent: "paper-card",
        onAccent: "cobalt",
        accentText: "paper-card",
        border: { token: "paper-card", mix: { alpha: 0.3 } },
        link: "paper-card",
        focusRing: "paper-card",
      },
    },
  ],
  defaultScheme: "paper",
  typeset: {
    fonts: [
      { id: "barlow-condensed", family: "Barlow Condensed", fallback: "'Arial Narrow', sans-serif", source: "google", weights: [400, 500, 600, 700] },
      { id: "barlow", family: "Barlow", fallback: "system-ui, sans-serif", source: "google", weights: [400, 500, 600, 700] },
    ],
    roles: {
      display: { font: "barlow-condensed", weight: 600, tracking: 0.01, lineHeight: 0.95, uppercase: true },
      heading: { font: "barlow-condensed", weight: 600, tracking: 0, lineHeight: 1.1 },
      body: { font: "barlow", weight: 400, lineHeight: 1.55 },
      accent: { font: "barlow", weight: 600, tracking: 0.1, lineHeight: 1.4, uppercase: true },
      mono: { font: "barlow", weight: 500 },
    },
    scale: { baseMin: 16, baseMax: 18, ratioMin: 1.2, ratioMax: 1.3 },
  },
  shape: {
    radius: 3,
    borderWidth: 1,
    shadows: [
      { id: "plate-edge", name: "Plate edge", y: 1, blur: 0, inset: true, color: { token: "paper-card", mix: { alpha: 0.6 } } },
      { id: "hairline", name: "Hairline drop", y: 1, blur: 2, color: { token: "graphite", mix: { alpha: 0.12 } } },
    ],
  },
  buttons: [
    { id: "plate", name: "Plate", radius: "md", fontRole: "accent", weight: 600, uppercase: true, tracking: 0.08, paddingX: 6, paddingY: 3, hover: "darken", shadow: "plate-edge" },
    { id: "quiet", name: "Quiet", radius: "md", fontRole: "body", weight: 600, paddingX: 5, paddingY: 3, hover: "darken" },
  ],
  defaultButton: "plate",
  motion: { profile: "subtle", entrance: "rise", durationBase: 260 },
  brand: {
    voice: {
      tone: "Direct, concrete, one professional to another. Short sentences. Dimensions, prices and delays before adjectives. Belgian French, Flemish for Dutch.",
      avoid: ["révolutionnaire", "passion", "solutions", "leader", "n'hésitez pas", "haut de gamme"],
    },
  },
  surfaces: {
    gradients: [
      ...builtInGradients,
      {
        id: "brushed",
        name: "Brushed steel",
        kind: "linear",
        angle: 100,
        stops: [
          { role: "backgroundAlt", alpha: 0.35, at: 0 },
          { role: "surface", alpha: 0.75, at: 18 },
          { role: "background", alpha: 0, at: 38 },
          { role: "backgroundAlt", alpha: 0.3, at: 56 },
          { role: "surface", alpha: 0.8, at: 78 },
          { role: "backgroundAlt", alpha: 0.4, at: 100 },
        ],
      },
      {
        id: "polished",
        name: "Polished steel",
        kind: "conic",
        angle: 200,
        x: 30,
        y: 20,
        stops: [
          { role: "surface", alpha: 0.9, at: 0 },
          { role: "background", alpha: 0, at: 25 },
          { role: "backgroundAlt", alpha: 0.35, at: 50 },
          { role: "surface", alpha: 0.8, at: 72 },
          { role: "background", alpha: 0, at: 100 },
        ],
      },
    ],
  },
  flavor: { id: "grounded" },
});
