import { builtInGradients, defineTheme } from "../schema";

/**
 * HM Froid "Cobalt Chapters": mineral paper, graphite and brushed inox, with
 * cobalt as the rim light and two full cobalt chapters on the landing page
 * (trades and FAQ). Steel is never a flat fill: it is the inox texture or the
 * `brushed`/`polished` gradients, so it reads as metal and not as grey.
 */
export const hmFroidTheme = defineTheme({
  id: "hm-froid",
  name: "HM Froid Inox",
  description: "Brushed stainless steel, graphite and paper white with a single cobalt accent. Sharp but safe: 3px radius, hairline borders.",
  modeStrategy: "light",
  palette: [
    { id: "cobalt", name: "Cobalt", group: "brand", locked: true, value: "#155bc2", description: "The one accent: links, eyebrows, status and a single band per page. Inherits the old HM blue. Never a button fill on paper." },
    { id: "cobalt-dark", name: "Cobalt dark", group: "brand", value: "#0e438f", description: "Pressed and shadow side of cobalt; the deep end of the cobalt chapters." },
    { id: "cobalt-light", name: "Cobalt light", group: "brand", value: "oklch(0.8 0.08 255)", description: "Links and eyebrows on graphite." },
    { id: "steel", name: "Steel", group: "accent", value: "#c6ceca", description: "Plate background. Only ever shown through the brushed or polished gradient." },
    { id: "steel-dark", name: "Steel dark", group: "accent", value: "#8b908c", description: "Shadow side of the plate; borders on steel." },
    { id: "chrome", name: "Chrome", group: "accent", value: "oklch(0.95 0.002 235)", description: "Highlight sweep on steel; raised surfaces on the plate." },
    { id: "paper", name: "Paper", group: "neutral", value: "#f2f4f2", description: "Page background: a cool mineral off-white." },
    { id: "paper-bright", name: "Paper bright", group: "neutral", value: "#fafbfa", description: "Lifted bands on paper: catalogue, showroom." },
    { id: "paper-card", name: "Paper card", group: "neutral", value: "oklch(1 0 0)", description: "Cards and inputs on paper: true white." },
    { id: "line", name: "Hairline", group: "neutral", value: "oklch(0.88 0.004 240)", description: "Borders on paper." },
    { id: "ash", name: "Ash", group: "neutral", value: "#70756f", description: "Muted text on paper." },
    { id: "graphite", name: "Graphite", group: "neutral", value: "#202321", description: "Body text; dark bands (utility bar, footer)." },
    { id: "ink-soft", name: "Ink soft", group: "neutral", value: "#414541", description: "The second line of a heading, set in a lighter graphite." },
    { id: "graphite-raised", name: "Graphite raised", group: "neutral", value: "oklch(0.26 0.006 250)", description: "Cards on graphite." },
    { id: "graphite-line", name: "Graphite line", group: "neutral", value: "oklch(0.35 0.006 250)", description: "Borders on graphite." },
  ],
  schemes: [
    {
      id: "paper",
      name: "Paper canvas",
      description: "Default page background. Catalogue, text pages, forms. Buttons are graphite; cobalt is reserved for links and eyebrows.",
      light: {
        background: "paper",
        backgroundAlt: "chrome",
        text: "graphite",
        textMuted: "ash",
        heading: "graphite",
        primary: "graphite",
        onPrimary: "chrome",
        secondary: "steel",
        onSecondary: "graphite",
        surface: "paper-card",
        onSurface: "graphite",
        accent: "steel",
        onAccent: "graphite",
        accentText: "cobalt",
        border: "line",
        link: "cobalt",
        focusRing: "cobalt",
      },
    },
    {
      id: "plate",
      name: "Steel plate",
      description: "The metal: hero, CTA band, product-card hover. Pair with the brushed or polished gradient and the brushed-lines texture.",
      light: {
        background: "steel",
        backgroundAlt: "steel-dark",
        text: "graphite",
        textMuted: { token: "graphite", mix: { alpha: 0.72 } },
        heading: "graphite",
        primary: "graphite",
        onPrimary: "chrome",
        secondary: "cobalt",
        onSecondary: "paper-card",
        surface: "chrome",
        onSurface: "graphite",
        accent: "graphite",
        onAccent: "chrome",
        accentText: { token: "cobalt", mix: { lightness: -0.07 } },
        border: "steel-dark",
        link: "graphite",
        focusRing: "cobalt",
      },
    },
    {
      id: "graphite",
      name: "Graphite band",
      description: "Dark bands: hero plinth, footer, trust strip.",
      light: {
        background: "graphite",
        backgroundAlt: "graphite-raised",
        text: "chrome",
        textMuted: "steel",
        heading: "paper-card",
        primary: "chrome",
        onPrimary: "graphite",
        secondary: "cobalt-light",
        onSecondary: "graphite",
        surface: "graphite-raised",
        onSurface: "chrome",
        accent: "cobalt",
        onAccent: "paper-card",
        accentText: "cobalt-light",
        border: "graphite-line",
        link: "cobalt-light",
        focusRing: "cobalt-light",
      },
    },
    {
      id: "cobalt",
      name: "Cobalt accent",
      description: "One band per page at most: rachat offer, newsletter.",
      light: {
        background: "cobalt",
        backgroundAlt: "cobalt",
        text: "paper-card",
        textMuted: { token: "paper-card", mix: { alpha: 0.8 } },
        heading: "paper-card",
        primary: "paper-card",
        onPrimary: "cobalt",
        secondary: "graphite",
        onSecondary: "paper-card",
        surface: { token: "cobalt", mix: { lightness: -0.08 } },
        onSurface: "paper-card",
        accent: "paper-card",
        onAccent: "cobalt",
        accentText: "paper-card",
        border: { token: "paper-card", mix: { alpha: 0.3 } },
        link: "paper-card",
        focusRing: "paper-card",
      },
    },
  ],
  defaultScheme: "paper",
  typeset: {
    fonts: [
      { id: "barlow-condensed", family: "Barlow Condensed", fallback: "'Arial Narrow', sans-serif", source: "google", weights: [600, 700] },
      { id: "manrope", family: "Manrope", fallback: "Arial, sans-serif", source: "google", weights: [400, 500, 600, 700, 800] },
    ],
    roles: {
      display: { font: "barlow-condensed", weight: 700, tracking: 0.01, lineHeight: 0.95, uppercase: true },
      heading: { font: "barlow-condensed", weight: 600, tracking: 0, lineHeight: 1.1 },
      body: { font: "manrope", weight: 400, lineHeight: 1.65 },
      accent: { font: "manrope", weight: 700, tracking: 0.1, lineHeight: 1.4, uppercase: true },
      mono: { font: "manrope", weight: 500 },
    },
    scale: { baseMin: 16, baseMax: 18, ratioMin: 1.2, ratioMax: 1.3 },
  },
  shape: {
    radius: 3,
    borderWidth: 1,
    shadows: [
      { id: "plate-edge", name: "Plate edge", y: 1, blur: 0, inset: true, color: { token: "paper-card", mix: { alpha: 0.6 } } },
      { id: "hairline", name: "Hairline drop", y: 1, blur: 2, color: { token: "graphite", mix: { alpha: 0.12 } } },
    ],
  },
  buttons: [
    { id: "plate", name: "Plate", radius: "md", fontRole: "accent", weight: 600, uppercase: true, tracking: 0.08, paddingX: 6, paddingY: 3, hover: "darken", shadow: "plate-edge" },
    { id: "quiet", name: "Quiet", radius: "md", fontRole: "body", weight: 600, paddingX: 5, paddingY: 3, hover: "darken" },
  ],
  defaultButton: "plate",
  motion: { profile: "subtle", entrance: "rise", durationBase: 260 },
  brand: {
    voice: {
      tone: "Direct, concrete, one professional to another. Short sentences. Dimensions, prices and delays before adjectives. Belgian French, Flemish for Dutch.",
      avoid: ["révolutionnaire", "passion", "solutions", "leader", "n'hésitez pas", "haut de gamme"],
    },
  },
  surfaces: {
    gradients: [
      ...builtInGradients,
      {
        id: "brushed",
        name: "Brushed steel",
        kind: "linear",
        angle: 100,
        stops: [
          { role: "backgroundAlt", alpha: 0.35, at: 0 },
          { role: "surface", alpha: 0.75, at: 18 },
          { role: "background", alpha: 0, at: 38 },
          { role: "backgroundAlt", alpha: 0.3, at: 56 },
          { role: "surface", alpha: 0.8, at: 78 },
          { role: "backgroundAlt", alpha: 0.4, at: 100 },
        ],
      },
      {
        id: "polished",
        name: "Polished steel",
        kind: "conic",
        angle: 200,
        x: 30,
        y: 20,
        stops: [
          { role: "surface", alpha: 0.9, at: 0 },
          { role: "background", alpha: 0, at: 25 },
          { role: "backgroundAlt", alpha: 0.35, at: 50 },
          { role: "surface", alpha: 0.8, at: 72 },
          { role: "surface", alpha: 0.9, at: 100 },
        ],
      },
    ],
  },
  flavor: { id: "grounded" },
  // The landing page is built from the "chapters" kit; the build script fills its assets.
  kits: [{ id: "chapters" }],
});
